---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation dummy resource'


Conditions:
  HasNot: !Equals [ 'true', 'false' ]


Resources:
  NullResource:
    Type: 'Custom::NullResource'
    Condition: HasNot


Outputs:
  StackName:
    Value: !Ref 'AWS::StackName'
    Export:
      Name: !Sub 'LambdaStackName-${AWS::StackName}'
